# Site settings
title: Yu-Cheng Qiu | Ph.D in Physics
description: "This is a site sharing knowledge of physics. Please contact me if you have any inquiry."
url: "https://qiuyucheng-hep.github.io"
author:
  name: "Yu-Cheng Qiu"
  email: "ethanqiu@sjtu.edu.cn"
  url: "https://qiuyucheng-hep.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

collections:
   publications:

      

